name: Build and Release

on:
  push:
    tags:
      - 'v*'  # タグを push したら実行

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Python をセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 依存関係をインストール
        run: pip install pyinstaller

      - name: 実行ファイルをビルド（CSVを同梱）
        run: |
          pyinstaller --onefile --add-data "sensor_data50.csv;." data1.py

      - name: アーティファクトをアップロード
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: dist/

      - name: GitHub Releases にアップロード
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
