name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Python をセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 依存関係をインストール
        run: pip install pyinstaller

      - name: 実行ファイルをビルド（CSVを同梱）
        run: |
          pyinstaller --onefile --add-data "sensor_data50.csv;." data1.py

      - name: distフォルダにCSVをコピー（念のため）
        run: cp sensor_data50.csv dist/

      - name: dist/ と build/ を含む ZIP を作成
        run: |
          powershell Compress-Archive -Path dist, build -DestinationPath release.zip

      - name: アーティファクトをアップロード（ZIP）
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.zip

      - name: GitHub Releases にアップロード（ZIP）
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
